# Generated by Django 3.0.5 on 2022-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20220119_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
